[versions]
springBoot = "3.3.4"
swt = "3.127.0"

[libraries]
particle = { module = "io.github.bitfist:particle", version = "0.1.4" }
springBootPlatform = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "springBoot" }
springBootConfigurationProcessor = { module = "org.springframework.boot:spring-boot-configuration-processor", version.ref = "springBoot" }
# Test
junit = { module = "org.junit.jupiter:junit-jupiter", version = "5.11.3" }
mockito = { module = "org.mockito:mockito-core", version = "5.14.1" }
# SWT
swtLinux = { module = "org.eclipse.platform:org.eclipse.swt.gtk.linux.x86_64", version.ref = "swt" }
swtMacos = { module = "org.eclipse.platform:org.eclipse.swt.cocoa.macosx.aarch64", version.ref = "swt" }
swtWindows = { module = "org.eclipse.platform:org.eclipse.swt.win32.win32.x86_64", version.ref = "swt" }
# Plugins
semanticVersioning = { module = "com.github.jmongard:git-semver-plugin", version = "0.12.10" }
